CC = gcc
CFLAGS = -Iinclude -O2 -DBGLVL=2
TARGET = bin\app.exe

SRCDIR = src
OBJDIR = build

SRC = main.c data.c

RMCMD = del /f

OBJ = $(SRC:%.c=%.o)
OBJS=$(OBJ:%=$(OBJDIR)/%) 

$(TARGET): $(OBJS)
	$(CC) $^ -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@


.PHONY: all clean cleanall

clean:
	$(RMCMD) $(TARGET)

cleanall:
	$(RMCMD) $(TARGET)
	$(RMCMD) build\*.o
	
	


 
	